# Generated by Django 3.2.14 on 2022-11-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_watchlist', '0006_auto_20221108_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='sum_rating',
            field=models.IntegerField(default=0),
        ),
    ]
