# Generated by Django 3.2.14 on 2022-11-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_watchlist', '0008_remove_watchlist_sum_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='sum_rating',
            field=models.IntegerField(default=0),
        ),
    ]
